### ISSUE TITLE
Unable to install with zef

### ISSUE THREAD

**Issue by tbrowder** [CurtTilmes/Perl6-GraphQL#10]
Fails usually saying words to the effect that "wrap-text" cannot be found.

**Comment by coke** [comment]
The problem is, I'm guessing, that the requirement of "Text::Wrap" needs to be more specific - by just saying the name of the class, you're getting the version from the module `_`, not the version from the eponymous `Text::Wrap` - and these each provide a different routine to do the wrapping.

If you update graphQL's depends to include the auth of the `Text::Wrap` module, this should resolve @tbrowder's issue.

**Comment by coke** [comment]
This should fix it: change the dependency in META6.json from a bare

```
Text::Wrap
```

to 

```
Text::Wrap:auth<github:jkramer>
```

**Comment by tbrowder** [comment]
Not quite fixed. The META6.json also needs an "auth" entry like this:

    "auth": "github:jkramer",

Zef does not use the "author" field for the module's identity.

I can make that fix as a PR, or you could fix it and then I'll take it over. 

I think it's best fixed before I take it over.

**Comment by coke** [comment]
> Not quite fixed. The META6.json also needs an "auth" entry like this:

That's in the Text::Wrap META6.json, not here. You should open a ticket on that module for that issue. Thanks, I should have noted that in my original comment.

**Comment by tbrowder** [comment]
My bad, I'm still confusing the two modules. I fixed Text::Wrap locally and Curt's module works fine.

I also submitted a PR to Text::Wrap.

**Comment by tbrowder** [comment]
The author of Text::Wrap fixed its problem.

Closing this.
